### PR TITLE
Failing - trying to return AJAX response body

### PR DESCRIPTION
**Pull request by BenRoss92**
Issue: Trying to return result of AJAX request (i.e. the response body)
- can only console.log it. Trying to make code wait for AJAX request to finish before returning result.

N.B.

Just trying to get 'lib/firstFile.js' file to work on its own, so just run 'node lib/firstFile.js' to see what's being console-logged.

See comments in 'lib/firstFile.js' for better explanation of the issue.

### CODE REVIEW

File: lib/firstFile.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+  }
+
+  this.makeRequest = function() {
+
+    // Passing options property and callback function into `request` function from npm package
+    request(this.options, callback);
+
+    // Tried passing `returnBody` as a callback - not
+    // - returning a TypeError: "returnBody is not a function"
+    function callback(error, response, body, returnBody) {
```
Comment (Jbarget) [inline lib/firstFile.js]: if you look at the docs for the `request` library you'll see that the "callback" function only takes 3 arguments 

https://github.com/request/request#super-simple-to-use

```
function (error, response, body) {
}
```

so you've added a 4th argument which isnt given by the request module so it is "undefined"

File: lib/firstFile.js [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+      return results;
+    }
+  }
+
+}
+
+// Search for articles related to 'brexit'
+var apiRequest = new ApiRequest("brexit");
+// Attempting to return the response body
+console.log(apiRequest.makeRequest());
```
Comment (Jbarget) [inline lib/firstFile.js]: this wont work as the `makeRequest` function doesnt have a `return` value

File: README.md [hunk 3]
```diff
@@ -1,5 +1,28 @@
 # Headline Fetcher 2
 
+## Running the app
+
+### Running locally (on a Mac)
```
Comment (Jbarget) [inline README.md:5]: good instructions

**Review by Jbarget — COMMENTED** [review]
i've sent you a facebook message with a link to a website that might help

essentially what you're trying to do by console logging the return value of `this.makeRequest` simply wont work asynchronus functions

i'll push up a branch with an example of something

**Comment by Jbarget** [comment]
can you add me as a to collaborator to this repo?

**Comment by BenRoss92** [comment]
Hey Just, yep sure, thanks for taking a look!

**Comment by BenRoss92** [comment]
Here's the link: https://github.com/BenRoss92/headline_fetcher/invitations

File: lib/apiRequest.js [hunk 4]
```diff
@@ -0,0 +1,55 @@
+require('dotenv').config(); // Loads FT API Key from '.env' file in root of project
+var request = require('request'); // Using 'request' package for AJAX requests - https://github.com/request/request
+
+function makeRequest(callback, searchTerm="") {
```
Comment (Jbarget) [inline lib/apiRequest.js:4]: convention is that `callback` is the last argument to a function

```js
function makeRequest(searchTerm = "", callback) {
```

File: routes/index.js [hunk 5]
```diff
@@ -1,66 +1,13 @@
...
-      var headline = {
-         "title": item.title.title,
-         "summary": item.summary.excerpt,
-         "editorial": item.editorial.byline
-      }
-      headlines.push(headline);
+  apiRequest.makeRequest(renderHeadlines);
 
-    });
+  function renderHeadlines(headlines) {
```
Comment (Jbarget) [inline routes/index.js:10]: this function is used as a callback and needs to be able to handle an error, by convention in Node there are "error first callbacks"

http://thenodeway.io/posts/understanding-error-first-callbacks/

```js
function renderHeadlines(err, headlines) {
     if (err) return res.status(500).send({ error: 'something blew up' });
    res.render('index', { title: 'Headline Fetcher', headlines: headlines });
}
```

File: lib/apiRequest.js [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+    headlineData.forEach(function(headline) {
+      headline = {
+        "title": headline.title.title,
+        "summary": headline.summary.excerpt,
+        "editorial": headline.editorial.byline
+      }
+      headlines.push(headline);
+    });
+
+    return callback(headlines);
```
Comment (Jbarget) [inline lib/apiRequest.js:48]: because the function signature of our callback on line 10 of `routes/index.js` is `callback(err, headlines)` we need to change this to:
```js
return callback(null, headlines);
```

File: lib/apiRequest.js [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+  var options = {
+    method: 'post',
+    body: params,
+    json: true,
+    url: url + '?apiKey=' + apiKey
+  }
+
+  request(options, function(error, response, body) {
+    if (error) {
+      throw error;
```
Comment (Jbarget) [inline lib/apiRequest.js:30]: rather than `throw`ing the error we can now handle the error case gracefully with:
```js
if (error) return callback(error)
```

which will call `renderHeadlines` with the error

File: routes/index.js [hunk 8]
```diff
@@ -1,66 +1,13 @@
...
-    var headlines = new Array();
-
-    results.forEach(function(item) {
-      var headline = {
-         "title": item.title.title,
-         "summary": item.summary.excerpt,
-         "editorial": item.editorial.byline
-      }
-      headlines.push(headline);
+  apiRequest.makeRequest(renderHeadlines);
```
Comment (Jbarget) [inline routes/index.js:8]: this call now needs to be:

```js
apiRequest.makeRequest("search term", renderHeadlines);
```

because we changed the function signature of the `makeRequest ` function on line 4 of `apiRequest.js`
